# Generated by Django 3.2.3 on 2021-05-29 07:36

import django.core.validators
from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinput',
            name='file_transaction',
        ),
        migrations.AddField(
            model_name='fileinput',
            name='file_transactions',
            field=models.FileField(default=None, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx']), main.validators.validate_file_content], verbose_name='Транзакционнае данные'),
        ),
        migrations.AddField(
            model_name='fileinput',
            name='min_conf',
            field=models.FloatField(default=0.1, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='fileinput',
            name='min_support',
            field=models.FloatField(default=0.1, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='fileinput',
            name='file_customers',
            field=models.FileField(default=None, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx']), main.validators.validate_file_content], verbose_name='Данные о клиентах'),
        ),
        migrations.AlterField(
            model_name='fileinput',
            name='file_goods',
            field=models.FileField(default=None, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx']), main.validators.validate_file_content], verbose_name='Данные о товарах'),
        ),
    ]
