# Generated by Django 3.2.3 on 2021-05-29 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210529_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_class', models.CharField(max_length=200)),
                ('left', models.CharField(max_length=200)),
                ('left_support', models.FloatField()),
                ('right', models.CharField(max_length=200)),
                ('right_support', models.FloatField()),
                ('support', models.FloatField()),
                ('confidence', models.FloatField()),
                ('lift', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='fileinput',
            name='clusters',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fileinput',
            name='min_conf',
            field=models.FloatField(default=0.01, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='fileinput',
            name='min_support',
            field=models.FloatField(default=0.01, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
