# Generated by Django 3.2.3 on 2021-05-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210529_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cluster_id', models.CharField(max_length=200)),
                ('mean_cheque', models.FloatField(default=1)),
                ('return_proba', models.FloatField(default=1)),
                ('purchases', models.TextField()),
            ],
        ),
    ]
