# Generated by Django 3.2.3 on 2021-05-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='id',
            new_name='customer_id',
        ),
    ]
